name: Build and deploy Node.js app to Azure Web App - journy

on:
  push:
    branches:
      - cloud
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./journy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./journy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5683F3801E704E079E344F36FF858E29 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B0F9E7C62C31451DBB90C176921DAFD5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4C4F0E53555A4726A9817A3C9A618785 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jounry'
          slot-name: 'Production'
          package: ./journy
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          OPEN_AI_ENDPOINT: ${{ secrets.OPEN_AI_ENDPOINT }}
          OPEN_AI_MODEL: ${{ secrets.OPEN_AI_MODEL }}
          OPEN_AI_DEPLOYMENT_NAME: ${{ secrets.OPEN_AI_DEPLOYMENT_NAME }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          # hello
